coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        branches:
          - main
        if_not_found: success
        only_pulls: false
